# -*- coding: utf-8 -*-
"""geo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1icOxX3_a3D_vMMB_96Aal8l2FlU7jynE
"""

class Rectangle :
    def __init__(self, length, width):
        self.length = length
        self.width = width

    def rectangle_area(self):
         return self.length*self.width

class Patch(object) :
    def __init__(self,object):
      self.object = object
      self.max = self.object.rectangle_area()
      self.patch = 0
    
    def __iter__(self):
      return self
    def __next__(self):
      if self.patch>=self.max:
        raise StopIteration
      else:
        self.patch +=1
        self.x = ((self.patch-1)//self.object.width) + 1
        self.y = self.patch - ((self.x - 1)*self.object.width)
        return list((self.x,self.y))